[Seat:*]
type=local
greeter-session=lightdm-greeter
autologin-user=nexus
autologin-user-timeout=0
autologin-in-background=false
pam-autologin-service=lightdm-autologin
user-session=xfce
autologin-session=xfce
