[Seat:*]
type=local
greeter-session=lightdm-greeter
greeter-hide-users=true
allow-guest=false
autologin-user=nexus
autologin-user-timeout=0
autologin-in-background=false
pam-autologin-service=lightdm-autologin
user-session=nexus
autologin-session=nexus
