#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR=/build/os
WEB_DIR=/build/dashboard

mkdir -p "$BUILD_DIR/config/includes.chroot/opt/nexus-control"
rsync -a --delete "$WEB_DIR/" "$BUILD_DIR/config/includes.chroot/opt/nexus-control/"

cd "$BUILD_DIR"
# Remove generated build stages while keeping the mounted live-build package
# cache so an interrupted network transfer does not force a full redownload.
lb clean --chroot --binary --stage --source >/dev/null 2>&1 || true
# live-build automatically executes auto/config and auto/build when those
# wrappers are present. This entrypoint owns the build sequence, so hide the
# wrappers temporarily to avoid them calling themselves recursively.
mv auto/config auto/config.wrapper
mv auto/build auto/build.wrapper
restore_wrappers() {
  mv auto/config.wrapper auto/config
  mv auto/build.wrapper auto/build
}
trap restore_wrappers EXIT

lb config \
  --distribution bookworm \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --binary-images iso-hybrid \
  --debian-installer live \
  --linux-packages linux-image \
  --memtest none \
  --apt-recommends true \
  --mirror-bootstrap "http://ftp.es.debian.org/debian" \
  --mirror-chroot "http://ftp.es.debian.org/debian" \
  --mirror-binary "http://ftp.es.debian.org/debian" \
  --mirror-chroot-security "http://ftp.es.debian.org/debian-security" \
  --mirror-binary-security "http://ftp.es.debian.org/debian-security" \
  --apt-options "-y -o Acquire::ForceIPv4=true -o Acquire::Retries=10 -o Acquire::http::Timeout=60 -o Acquire::https::Timeout=60 -o Acquire::http::Pipeline-Depth=0" \
  --bootappend-live "boot=live components live-config.username=nexus username=nexus locales=en_US.UTF-8 keyboard-layouts=us"
lb build
trap - EXIT
restore_wrappers

ISO_PATH="$(find "$BUILD_DIR" -maxdepth 1 -type f -name '*.iso' -print -quit)"
if [ -z "$ISO_PATH" ]; then
  echo "No ISO was generated by live-build" >&2
  exit 1
fi

mkdir -p /out
cp "$ISO_PATH" /out/nexus-os-0.1.0-amd64.iso
(cd /out && sha256sum nexus-os-0.1.0-amd64.iso > nexus-os-0.1.0-amd64.iso.sha256)
